#!/usr/bin/env node

var tilelive = require('tilelive')
var queue = require('queue-async')
var readSample = require('./lib/read-sample')
var writeTile = require('./lib/write-tile')
var argv = require('minimist')(process.argv.slice(2))

var input = argv._[0] // tilelive uri
tilelive.auto(input)
var output = argv._[1] // output dir

tilelive.load(input, function (err, source) {
  if (err) { throw err }

  var q = queue(3) // limit the number of simulatenous requests

  readSample(argv)
  .on('data', function (tile) {
    q.defer(function (done) {
      writeTile(output, source, tile, done, false, '.jpg')
    })
  })
  .on('end', function () {
    q.awaitAll(function (err) {
      if (err) { throw err }
    })
  })
})

