#!/usr/bin/env node

var fs = require('fs')
var path = require('path')
var PNG = require('pngjs').PNG
var readSample = require('./lib/read-sample')
var through = require('through2')
var createClassLookup = require('./lib/lookup-class')

var classes = JSON.parse(fs.readFileSync(process.argv[2]))
var getClass = createClassLookup(classes)
var labels = process.argv[3]

readSample()
.pipe(through.obj(write, end))
.pipe(process.stdout)

var frequencies = []
function write (tile, _, next) {
  var file = path.join(labels, tile.join('-') + '.png')
  fs.createReadStream(file).pipe(new PNG()
    .on('parsed', function () {
      for (var y = 0; y < this.height; y++) {
        for (var x = 0; x < this.width; x++) {
          var r = (this.width * y + x) << 2
          var g = r + 1
          var b = r + 2
          var index = getClass(this.data[r], this.data[g], this.data[b])
          frequencies[index] = frequencies[index] || 0
          frequencies[index] += 1
        }
      }
      next()
    })
  )
}

function end (cb) {
  this.push('label,frequency\n')
  frequencies.forEach((f, i) => this.push(i + ',' + f + '\n'))
  cb()
}
