#!/usr/bin/env node

var split = require('split')
var through = require('through2')

process.stdin.pipe(split())
.pipe(through.obj(write, end))
.pipe(process.stdout)

var frequencies
var imageCounts

function write (line, _, next) {
  if (line.trim().length === 0) { return next() }
  line = line.split(',')
  // skip header line
  if (!frequencies) {
    frequencies = line.slice(1).map((x) => 0)
    imageCounts = [].concat(frequencies)
    return next()
  }

  line.slice(1).forEach((count, i) => {
    count = Number(count)
    frequencies[i] += Number(count)
    if (count > 0) {
      imageCounts[i] += 1
    }
  })
  next()
}

function end (cb) {
  this.push('label,frequency,image_count\n')
  frequencies.forEach((f, i) => this.push([i, f, imageCounts[i]].join(',') + '\n'))
  cb()
}

