#!/usr/bin/env node

var fs = require('fs')
var path = require('path')
var PNG = require('pngjs').PNG
var readSample = require('./lib/read-sample')
var through = require('through2')
var createClassLookup = require('./lib/lookup-class')

var classes = JSON.parse(fs.readFileSync(process.argv[2]))
var getClass = createClassLookup(classes)
var labels = process.argv[3]

readSample()
.pipe(through.obj(write))
.pipe(process.stdout)

var first = true

function write (tile, _, next) {
  var file = path.join(labels, tile.join('-') + '.png')
  if (!fs.existsSync(file)) {
    console.error('Missing file: ' + file)
    return next()
  }

  var stream = this

  fs.createReadStream(file).pipe(new PNG()
    .on('parsed', function () {
      var currentImageFrequencies = classes.map((x) => 0).concat([0])
      for (var y = 0; y < this.height; y++) {
        for (var x = 0; x < this.width; x++) {
          var r = (this.width * y + x) << 2
          var g = r + 1
          var b = r + 2
          var index = getClass(this.data[r], this.data[g], this.data[b])
          currentImageFrequencies[index] += 1
        }
      }
      if (first) {
        first = false
        var classNames = classes.map((c) => c.name).concat(['Background'])
        stream.push(['#source', 'z', 'x', 'y'].concat(classNames).join(' ') + '\n')
      }
      stream.push([tile.source].concat(tile, currentImageFrequencies).join(' ') + '\n')
      next()
    })
  )
}

