#!/usr/bin/env node

var readSample = require('./lib/read-sample')
var through = require('through2')
var argv = require('minimist')(process.argv.slice(2))

readSample(argv)
.pipe(through.obj(write, end))
.pipe(process.stdout)

var frequencies
var imageCounts

function write (tile, _, next) {
  if (!frequencies) {
    frequencies = tile.data.map((x) => 0)
    imageCounts = [].concat(frequencies)
  }

  tile.data.forEach((count, i) => {
    count = Number(count)
    frequencies[i] += Number(count)
    if (count > 0) {
      imageCounts[i] += 1
    }
  })
  next()
}

function end (cb) {
  this.push('label,frequency,image_count\n')
  frequencies.forEach((f, i) => this.push([i, f, imageCounts[i]].join(',') + '\n'))
  cb()
}

