#!/usr/bin/env node

var path = require('path')
var Vector = require('tilelive-vector')
var tilelive = require('tilelive')
require('mbtiles').registerProtocols(tilelive)
var queue = require('queue-async')
var argv = require('minimist')(process.argv.slice(2))

var style = require('./lib/style')
var readSample = require('./lib/read-sample')
var writeTile = require('./lib/write-tile')

var input = argv._[0] // usually an osm qa tiles mbtiles file
var layers = require(path.resolve(argv._[1])) // json file defining classes
var output = argv._[2] // output dir
var labelRatio = argv._[3]

init(input, style(layers), function (err, vector) {
  if (err) { throw err }

  var q = queue(5) // TODO: abstract magic number

  readSample(argv)
  .on('data', function (tile) {
    q.defer(function (done) {
      //skip images which are blank if the label ratio > 0
      //helps with case where images with a label_ratio>0 are sparse
      if(labelRatio > 0){
        writeTile(output, vector, tile, done, true, '.png')
      }else{
        writeTile(output, vector, tile, done, false, '.png')
      }
    })
  })
  .on('end', function () {
    q.awaitAll(function (err) { if (err) { throw err } })
  })
})

function init (source, style, cb) {
  if (!/^.+:\/\//.test(source)) {
    source = 'mbtiles://' + path.resolve(source)
  } else {
    tilelive.auto(source)
  }

  console.log('Reading from source', source)
  /* eslint-disable no-new */
  new Vector({
    xml: style,
    source: source
  }, cb)
}
