#!/usr/bin/env node

var fs = require('fs')
var exec = require('child_process').exec
var split = require('split')

var tiles = process.argv[2]
var trainSize = process.argv[3]

var sample
var i = -1

countLines(tiles, function (err, total) {
  if (err) { throw err }
  fs.createReadStream(tiles)
  .pipe(split())
  .on('data', function (line) {
    if (!line) return
    if (!sample) {
      sample = []
      while (sample.length < trainSize && sample.length < total) {
        var l = Math.floor(Math.random() * total)
        if (sample.indexOf(l) < 0) { sample.push(l) }
      }
      sample.sort((a, b) => (a - b))
    }

    if (sample[0] === i++) {
      console.log(line)
      sample.shift()
    }
  })
})

function countLines (file, cb) {
  exec('wc -l ' + file, function (err, result) {
    if (err) { return cb(err) }
    cb(null, +result.trim().split(' ')[0])
  })
}
